import { useMemo, useState } from 'react'
import { Gauge, Layers3, Pencil, Plus, Users, Target } from 'lucide-react'
import type { FeatureRequest, JiraTicket, ProjectEntity, Squad, SprintPlan } from '../services/localState'
import { SpecialtyTagPills } from './DeveloperSpecialties'

type Props = { squads: Squad[]; tickets: JiraTicket[]; projects: ProjectEntity[]; features: FeatureRequest[]; sprintPlans: SprintPlan[]; selectedSquadId: string; onSelectSquad: (id: string) => void; onCreateSquad: (name: string) => void; onRenameSquad: (id: string, name: string) => void; onAddPerson: () => void; onEditPerson: (developer: import('../services/localState').Developer) => void }

export function TeamsManagementPanel({ squads, tickets, projects, features, sprintPlans, selectedSquadId, onSelectSquad, onCreateSquad, onRenameSquad, onAddPerson, onEditPerson }: Props) {
  const [newName, setNewName] = useState('')
  const selected = squads.find((squad) => squad.id === selectedSquadId) || squads[0]
  const stats = useMemo(() => {
    if (!selected) return { raw: 0, safe: 0, assigned: 0, planned: 0, projects: [], features: 0, strengths: [] as string[] }
    const memberIds = new Set(selected.developers.map((developer) => developer.id))
    const scope = tickets.filter((ticket) => memberIds.has(ticket.assignee))
    const assigned = scope.reduce((sum, ticket) => sum + ticket.story_points, 0)
    const planned = scope.filter((ticket) => ticket.sprint_id).reduce((sum, ticket) => sum + ticket.story_points, 0)
    const projectIds = new Set(scope.map((ticket) => ticket.project_id).filter(Boolean))
    const strengthMap = new Map<string, number>()
    selected.developers.forEach((developer) => (developer.specialty_tags || []).forEach((tag) => strengthMap.set(tag.label, (strengthMap.get(tag.label) || 0) + 1)))
    return { raw: selected.developers.reduce((sum, developer) => sum + developer.raw_capacity, 0), safe: selected.developers.reduce((sum, developer) => sum + developer.raw_capacity * .8, 0), assigned, planned, projects: Array.from(projectIds).map((id) => projects.find((project) => project.id === id)?.name).filter(Boolean), features: features.filter((feature) => projectIds.has(feature.project_id)).length, strengths: Array.from(strengthMap.entries()).sort((a, b) => b[1] - a[1]).slice(0, 6).map(([name, count]) => `${name} (${count})`) }
  }, [selected, tickets, projects, features])

  function createSquad() { if (newName.trim()) { onCreateSquad(newName.trim()); setNewName('') } }
  function rename() { if (selected) { const name = window.prompt('Team name', selected.name); if (name?.trim()) onRenameSquad(selected.id, name.trim()) } }

  return <div className="forge-management-page" data-testid="teams-page">
    <header className="hero-panel"><div className="panel-head"><div><div className="eyebrow">Teams</div><h1 className="page-title">Squads & delivery teams</h1><p className="hero-copy">Create squads, assign people, and understand delivery capacity, planned work, ownership, and team strengths.</p></div><button type="button" onClick={onAddPerson} style={buttonStyle}><Plus size={14} /> Assign person</button></div><div className="fact-strip"><span className="fact-pill"><Users size={11} /> {squads.length} squads</span><span className="fact-pill">{selected?.developers.length || 0} members</span><span className="fact-pill"><Gauge size={11} /> {stats.safe.toFixed(0)} SP safe capacity</span><span className="fact-pill">{stats.planned} SP planned</span></div></header>
    <div className="team-layout"><aside className="team-list"><div className="section-title">Teams</div>{squads.map((squad) => <button type="button" key={squad.id} className={`team-select ${selected?.id === squad.id ? 'selected' : ''}`} onClick={() => onSelectSquad(squad.id)}><strong>{squad.name}</strong><span>{squad.developers.length} people · {tickets.filter((ticket) => squad.developers.some((developer) => developer.id === ticket.assignee)).reduce((sum, ticket) => sum + ticket.story_points, 0)} SP</span></button>)}<div className="create-team"><input value={newName} onChange={(event) => setNewName(event.target.value)} onKeyDown={(event) => event.key === 'Enter' && createSquad()} placeholder="New team name" /><button type="button" onClick={createSquad} style={iconButtonStyle} aria-label="Create team"><Plus size={13} /></button></div></aside>
      {selected ? <main className="team-detail"><div className="card-title-row"><div><div className="eyebrow">Squad profile</div><h2>{selected.name}</h2></div><button type="button" onClick={rename} style={buttonStyle}><Pencil size={12} /> Rename</button></div><div className="team-metrics"><Metric icon={Gauge} label="Safe capacity" value={`${stats.safe.toFixed(0)} SP`} /><Metric icon={Target} label="Assigned" value={`${stats.assigned} SP`} /><Metric icon={Layers3} label="Planned" value={`${stats.planned} SP`} /><Metric icon={Users} label="Members" value={`${selected.developers.length}`} /></div><section className="team-section"><div className="section-title">People in this squad</div>{selected.developers.map((developer) => <div className="member-row" key={developer.id}><div><strong>{developer.name}</strong><div className="muted">{developer.ranking} · {developer.raw_capacity} SP raw</div><SpecialtyTagPills tags={developer.specialty_tags} compact /></div><button type="button" onClick={() => onEditPerson(developer)} style={iconButtonStyle} title="Edit person"><Pencil size={12} /></button></div>)}{selected.developers.length === 0 && <div className="muted">No people assigned. Use Assign person to add someone.</div>}</section><div className="team-columns"><section className="team-section"><div className="section-title">Projects & features</div><div className="muted">{stats.projects.join(', ') || 'No projects linked through work yet.'}</div><div className="stat-value" style={{ marginTop: 8 }}>{stats.features} features involved</div></section><section className="team-section"><div className="section-title">Squad strengths</div><div className="tag-row">{stats.strengths.map((strength) => <span className="status-chip good" key={strength}>{strength}</span>)}</div><div className="muted" style={{ marginTop: 8 }}>{sprintPlans.filter((sprint) => sprint.squad_id === selected.id && sprint.status !== 'complete').length} active or future sprints</div></section></div></main> : <div className="empty-management">Create a team to begin.</div>}</div>
  </div>
}
function Metric({ icon: Icon, label, value }: { icon: typeof Gauge; label: string; value: string }) { return <div className="management-metric"><Icon size={14} /><div className="stat-label">{label}</div><strong>{value}</strong></div> }
const buttonStyle = { display: 'inline-flex', alignItems: 'center', gap: '6px', border: '1px solid var(--cp-border)', background: 'rgba(0,229,255,.08)', color: 'var(--cp-cyan)', padding: '8px 10px', cursor: 'pointer', fontFamily: "'Share Tech Mono', monospace", textTransform: 'uppercase' as const, fontSize: '10px' }
const iconButtonStyle = { display: 'grid', placeItems: 'center', width: '28px', height: '28px', background: 'var(--cp-bg-3)', color: 'var(--cp-cyan)', border: '1px solid var(--cp-border)', cursor: 'pointer' }
